#!/bin/bash

# Usage:
#   bash cd_hit.sh <ProteinFAA> <NucleotideFNA> <OutputDir> <Prefix>
#
# <ProteinFAA>   : protein FASTA generated by Prodigal
# <NucleotideFNA>: nucleotide FASTA generated by Prodigal
# <OutputDir>    : output directory
# <Prefix>       : output prefix

PROTEIN="$1"
NUCLEOTIDE="$2"
OUTDIR="$3"
PREFIX="$4"

mkdir -p "${OUTDIR}"

# CD-HIT clustering (95% identity)
cd-hit \
    -i "${PROTEIN}" \
    -o "${OUTDIR}/${PREFIX}_protein_nr.faa" \
    -c 0.95 \
    -aS 0.9 \
    -T 4 \
    -M 200000

# Extract representative IDs
seqkit fx2tab "${OUTDIR}/${PREFIX}_protein_nr.faa" | \
    cut -f1 > "${OUTDIR}/rep_ids.txt"

# Extract corresponding nucleotide sequences
seqkit grep \
    -f "${OUTDIR}/rep_ids.txt" \
    -n "${NUCLEOTIDE}" \
    > "${OUTDIR}/${PREFIX}_nucleotide_nr.fna"

# Remove descriptions from FASTA headers
seqkit replace \
    -p " .*" \
    -r "" \
    "${OUTDIR}/${PREFIX}_protein_nr.faa" \
    > "${OUTDIR}/${PREFIX}_renamed_protein_nr.faa"

seqkit replace \
    -p " .*" \
    -r "" \
    "${OUTDIR}/${PREFIX}_nucleotide_nr.fna" \
    > "${OUTDIR}/${PREFIX}_renamed_nucleotide_nr.fna"
